repos:
-   repo: https://github.com/nix-community/nixpkgs-fmt
    rev: v1.2.0
    hooks:
    -   id: nixpkgs-fmt
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    -   id: trailing-whitespace
        exclude_types: [diff]
