"$schema" = 'https://starship.rs/config-schema.json'

palette = 'ayu_dark'

add_newline = false

[aws]
disabled = true

[gcloud]
disabled = true

[line_break]
disabled = true

[kubernetes]
symbol = "⎈ "
disabled = false

[palettes.ayu_dark]
color_fg0 = '#B3B1AD'
color_bg1 = '#0A0E14'
color_bg3 = '#1C212B'

color_blue   = '#53BDFA'
color_aqua   = '#90E1C6'
color_green  = '#91B362'
color_orange = '#F29668'
color_purple = '#FAE994'
color_red    = '#EA6C73'
color_yellow = '#F9AF4F'
